mongo:
  host: "127.0.0.1"
  port: 27017
  database: "ffa"
  auth:
    enabled: false
    user: "elb1to_is_1337"
    pass: "gangatronic"
    auth-db: "admin"
scoreboard:
  combat-tagged: "&f Combat: &d<seconds>s"
  title: "&d&lNA PRACTICE"
  lines:
    - "&7&m------------------------"
    - "&fPlaying FFA:"
    - "&d<kit>"
    - ""
    - "&f Kills: &d<kills>"
    - "&f Deaths: &d<deaths>"
    - ""
    - "&f Killstreak: <killstreak>"
    - "&f Players: &d<players>"
    - "<isCombatTagged>"
    - ""
    - "&fYour Ping: &d<ping> ms"
    - ""
    - "elb1to.me"
    - "&7&m------------------------"
messages:
  join:
    - " "
    - "&e&lPlaying FFA"
    - "&e ● Kit: &d<kit>"
    - "&e ● &fTo leave, do /ffa leave"
    - " "
  killstreak_broadcast:
    - " "
    - "&d&l<player> &e&lis on a &d&l<killstreak> Kill Streak&e&l!"
    - " "
  played_killed: "&d<victim> &ewas killed by &d<killer>&e."
  enter_spawn: "&aYou have entered the FFA spawn."
  exit_spawn: "&cYou have exited the FFA spawn."
  cannot_fight: "&cYou cannot fight at spawn."

kits:
  default:
    contents: "Default"
    armor: "IRON_SWORD"

maps: # config section
  spawn: # name
    type: lobby # type
    spawn: 0.0, 0.0, 0.0 # spawn
    min: -100.0, -100.0, -100.0 # min
    max: 100.0, 100.0, 100.0 # max
  forest:
    type: arena
    spawn: 0.0, 0.0, 0.0
    min: -100.0, -100.0, -100.0
    max: 100.0, 100.0, 100.0
